#!/bin/sh
set -eu

SCHEDULE="${SCHEDULE:-15 2 * * *}"
WILDDUCK_API="${WILDDUCK_API:-http://wildduck:8080}"
ARCHIVE_BASE="${ARCHIVE_BASE:-Archives}"
ARCHIVE_MONTHS="${ARCHIVE_MONTHS:-3}"
ARCHIVE_PATTERN="${ARCHIVE_PATTERN:-{base}/{year}/{month}}"
ARCHIVE_ALL_FOLDERS="${ARCHIVE_ALL_FOLDERS:-}"
ARCHIVE_INCLUDE_BASE="${ARCHIVE_INCLUDE_BASE:-}"
ARCHIVE_USERS="${ARCHIVE_USERS:-}"
ARCHIVE_PROGRESS="${ARCHIVE_PROGRESS:-}"
DRY_RUN="${DRY_RUN:-}"

cat > /etc/crontabs/root <<EOF
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

$SCHEDULE WILDDUCK_API=$WILDDUCK_API ARCHIVE_BASE=$ARCHIVE_BASE ARCHIVE_MONTHS=$ARCHIVE_MONTHS ARCHIVE_PATTERN=$ARCHIVE_PATTERN ARCHIVE_ALL_FOLDERS=$ARCHIVE_ALL_FOLDERS ARCHIVE_INCLUDE_BASE=$ARCHIVE_INCLUDE_BASE ARCHIVE_USERS=$ARCHIVE_USERS ARCHIVE_PROGRESS=$ARCHIVE_PROGRESS DRY_RUN=$DRY_RUN /usr/bin/python3 /app/auto-archive.py >> /var/log/auto-archive.log 2>&1
EOF

exec crond -f -l 2
